services:
  app:
    build: ./express-app
    image: saskarkhadka/express-app
    ports:
      - 8080:8080
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"


  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60
    container_name: watchtower
    command: --label-enable --cleanup
    restart: unless-stopped